name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: Deployment
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          cache-key: deploy
      - name: Build Hawk
        run: >-
          clojure -T:build jar
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
      - name: Deploy Hawk
        run: >-
          clojure -T:build deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
