name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kondo:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup
        with:
          cache-key: kondo
      - name: Run Kondo
        run: >-
          clojure -M:kondo --lint src test

  tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup
        with:
          cache-key: tests
      - name: Run tests
        run: >-
          clojure -X:dev:test
        env:
          CI: TRUE
